<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Seu site de eventos!</title>

        <!-- Bootstrap Core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="css/stylish-portfolio.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body>

        <!-- Navigation -->
        <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
                <li class="sidebar-brand">
                    <a href="#top"  onclick = $("#menu-close").click(); >Eventos</a>
                </li>
                <li>
                    <a href="#top" onclick = $("#menu-close").click(); >Home</a>
                </li>
                <li>
                    <a href="#about" onclick = $("#menu-close").click(); >Sobre</a>
                </li>
                <li>
                    <a href="#services" onclick = $("#menu-close").click(); >Serviços</a>
                </li>
                <li>
                    <a href="#cadastrar" onclick = $("#menu-close").click(); >Cadastro</a>
                </li>
                <li>
                    <a href="#portfolio" onclick = $("#menu-close").click(); >Eventos</a>
                </li>
                <li>
                    <a href="#contato" onclick = $("#menu-close").click(); >Contato</a>
                </li>
            </ul>
        </nav>

        <!-- Header -->
        <header id="top" class="header">
            <div class="text-vertical-center">
                <h1>Eventos</h1>
                <h3>Todos os eventos em um só lugar!</h3>
                <br>
                <a href="#about" class="btn btn-dark btn-lg">Saiba Mais!</a>
            </div>
        </header>

        <!-- About -->
        <section id="about" class="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>Nós oferecemos um site para divulgar todos os seus eventos!</h2>
                        <p class="lead">Saiba sobre todos os eventos que estão acontecendo e cadastre os seus!!!</p>
                    </div>
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>

        <!-- Services -->
        <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
        <section id="services" class="services bg-primary">
            <div class="container">
                <div class="row text-center">
                    <div class="col-lg-10 col-lg-offset-1">
                        <h2>O que temos!</h2>
                        <hr class="small">
                        <div class="row">
                            <div class="col-md-3 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                                    </span>
                                    <h4>
                                        <strong>Site 24/7</strong>
                                    </h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                    <a href="#" class="btn btn-light">Clique aqui!</a>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-compass fa-stack-1x text-primary"></i>
                                    </span>
                                    <h4>
                                        <strong>Localização</strong>
                                    </h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                    <a href="#" class="btn btn-light">Clique aqui!</a>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-flask fa-stack-1x text-primary"></i>
                                    </span>
                                    <h4>
                                        <strong>Química</strong>
                                    </h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                    <a href="#" class="btn btn-light">Clique aqui!</a>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-6">
                                <div class="service-item">
                                    <span class="fa-stack fa-4x">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-shield fa-stack-1x text-primary"></i>
                                    </span>
                                    <h4>
                                        <strong>Segurança</strong>
                                    </h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                    <a href="#" class="btn btn-light">Clique aqui!</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.col-lg-10 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>

        <!-- Callout -->
        <aside class="callout" id="cadastrar">

            <div class="text-vertical-center">
                <div class="container" style="text-align: center;padding-bottom: 10px;">
                    <h2>Cadastre seu evento agora!!!</h2>
                    <div class="row">
                        <form role="form" class="col-md-40 col-md-offset-4">
                            <div class="col-lg-6">
                                <div class="well well-sm"><strong style="color: #31b0d5"><span class="glyphicon glyphicon-asterisk"></span>Preenchimento obrigatório!</strong></div>
                                <div class="form-group">
                                    <label for="nome">Titulo</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="titulo" id="titulo" placeholder="Coloque o titulo aqui!" required>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <div class="input-group">
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Coloque seu email aqui!" required>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="data">Data e Hora</label>
                                    <div class="input-group">
                                        <input type="datetime-local" class="form-control" name="data" id="data" placeholder="Escolha a data!" required>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="local">Local</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="local" id="local" placeholder="Coloque o local aqui!" required>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="descricao">Descrição</label>
                                    <div class="input-group">
                                        <textarea name="descricao" id="descricao" class="form-control" rows="5" required></textarea>
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                                    </div>
                                </div>
                                <button type="submit" value="cadastrar" id="botaoCadastrar" class="btn btn-warning">Cadastrar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </aside>

        <!-- Portfolio -->
        <section id="portfolio" class="portfolio">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1 text-center">
                        <h2>Eventos</h2>
                        <hr class="small">
                        <div id="lista_de_eventos">
                            <div class="panel panel-default">
                                <button class="btn btn-dark" id="deletar" style="float:right" value="0">Deletar</button>
                                <button class="btn btn-dark" id="editar" style="float:right" value="0">Editar</button>
                                <div class="panel-heading">
                                    <p id="id_evento" style="float: top">id</p>
                                    <h3 class="panel-title">Titulo</h3>
                                </div>
                                <div class="panel-body">
                                    Descrição + data + email
                                </div>
                                <div class="panel-footer">
                                    Local
                                </div>
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                        <a class="btn btn-dark" id="mais">Mais Eventos</a>
                    </div>
                    <!-- /.col-lg-10 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>

        <!-- Call to Action -->
        <aside class="call-to-action bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <div id="evento_update">
                            
                        </div>
                    </div>
                </div>
            </div>
        </aside>

        <!-- Footer -->
        <footer>
            <div class="container" id="contato">
                <div class="row">
                    <div class="col-lg-10 col-lg-offset-1 text-center">
                        <h4><strong>Eventos!</strong>
                        </h4>
                        <p>IMD - Instituto Metrópole Digital<br>UFRN - Universidade Federal do Rio Grande do Norte</p>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-phone fa-fw"></i> (084) xxx-xxx-xxx</li>
                            <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:pedrovictor_caldas@hotmail.com">pedrovictor_caldas@hotmail.com</a>
                            </li>
                        </ul>
                        <br>
                        <ul class="list-inline">
                            <li>
                                <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                            </li>
                        </ul>
                        <hr class="small">
                        <p class="text-muted">Copyright &copy; Eventos 2015</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- jQuery -->
        <script src="js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="js/bootstrap.min.js"></script>

        <script src="js/scriptIndex.js"></script>

        <!-- Custom Theme JavaScript -->
        <script>
                        // Closes the sidebar menu
                        $("#menu-close").click(function (e) {
                            e.preventDefault();
                            $("#sidebar-wrapper").toggleClass("active");
                        });

                        // Opens the sidebar menu
                        $("#menu-toggle").click(function (e) {
                            e.preventDefault();
                            $("#sidebar-wrapper").toggleClass("active");
                        });

                        // Scrolls to the selected menu item on the page
                        $(function () {
                            $('a[href*=#]:not([href=#])').click(function () {
                                if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                                    var target = $(this.hash);
                                    target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                                    if (target.length) {
                                        $('html,body').animate({
                                            scrollTop: target.offset().top
                                        }, 1000);
                                        return false;
                                    }
                                }
                            });
                        });
        </script>

    </body>

</html>
